/**
 * POI categories map OpenMapTiles `poi` layer `class` values (and a few `subclass`) to our icon set.
 * https://openmaptiles.org/schema/#poi
 */
export const POI_CATEGORIES = [
  "fuel",
  "moto",
  "food",
  "shop",
  "lodging",
  "nature",
  "culture",
  "health",
  "transport",
  "services",
  "sport",
] as const;

export type PoiCategory = (typeof POI_CATEGORIES)[number];

export const POI_CATEGORY_COLORS: Record<PoiCategory, string> = {
  fuel: "#FF8A00",
  moto: "#E4002B",
  food: "#FF5A5F",
  shop: "#8B5CF6",
  lodging: "#3B82F6",
  nature: "#22A559",
  culture: "#B7791F",
  health: "#EF4444",
  transport: "#0EA5E9",
  services: "#64748B",
  sport: "#14B8A6",
};

/** OpenMapTiles poi class -> category */
export const POI_CLASS_TO_CATEGORY: Record<string, PoiCategory> = {
  fuel: "fuel",
  charging_station: "fuel",
  car: "moto",
  motorcycle: "moto",
  restaurant: "food",
  fast_food: "food",
  cafe: "food",
  bar: "food",
  beer: "food",
  ice_cream: "food",
  bakery: "food",
  shop: "shop",
  grocery: "shop",
  alcohol_shop: "shop",
  clothing_store: "shop",
  hardware: "shop",
  furniture: "shop",
  jewelry: "shop",
  shoe: "shop",
  books: "shop",
  gift: "shop",
  music: "shop",
  art_gallery: "culture",
  mobile_phone: "shop",
  laundry: "services",
  lodging: "lodging",
  campsite: "lodging",
  shelter: "lodging",
  park: "nature",
  garden: "nature",
  viewpoint: "nature",
  drinking_water: "nature",
  picnic_site: "nature",
  attraction: "culture",
  museum: "culture",
  castle: "culture",
  monument: "culture",
  place_of_worship: "culture",
  theatre: "culture",
  cinema: "culture",
  zoo: "culture",
  hospital: "health",
  doctors: "health",
  pharmacy: "health",
  dentist: "health",
  veterinary: "health",
  bus: "transport",
  railway: "transport",
  parking: "transport",
  bicycle_parking: "transport",
  motorcycle_parking: "transport",
  bicycle_rental: "transport",
  ferry_terminal: "transport",
  aerialway: "transport",
  police: "services",
  fire_station: "services",
  post: "services",
  bank: "services",
  atm: "services",
  toilets: "services",
  town_hall: "services",
  library: "services",
  school: "services",
  college: "services",
  townhall: "services",
  information: "services",
  stadium: "sport",
  pitch: "sport",
  sports_centre: "sport",
  swimming_pool: "sport",
  golf: "sport",
  playground: "sport",
};
