// Downloads the Noto Sans glyph PBFs used by the map style so labels render without network.
// Output: assets/glyphs/<fontstack>/<range>.pbf + src/map/glyphs.generated.ts
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const FONTS = ["Noto Sans Regular", "Noto Sans Bold", "Noto Sans Italic"];
// Latin, Latin-1, Latin Extended A/B, IPA, Greek, Cyrillic, general punctuation, currency, arrows
const RANGES = [0, 256, 512, 768, 1024, 8192, 8448];
const BASE = "https://tiles.openfreemap.org/fonts";

const entries = [];
for (const font of FONTS) {
  const dir = path.join(root, "assets/glyphs", font.replace(/ /g, "_"));
  fs.mkdirSync(dir, { recursive: true });
  for (const start of RANGES) {
    const range = `${start}-${start + 255}`;
    const file = path.join(dir, `${range}.pbf`);
    if (!fs.existsSync(file)) {
      const res = await fetch(`${BASE}/${encodeURIComponent(font)}/${range}.pbf`);
      if (!res.ok) throw new Error(`${font} ${range}: ${res.status}`);
      fs.writeFileSync(file, Buffer.from(await res.arrayBuffer()));
    }
    entries.push({ font, range, rel: `../../assets/glyphs/${font.replace(/ /g, "_")}/${range}.pbf` });
  }
}

const ts = `// Generated by scripts/fetch-glyphs.mjs – do not edit.
/* eslint-disable */
export const GLYPH_FILES: { font: string; range: string; asset: number }[] = [
${entries.map((e) => `  { font: "${e.font}", range: "${e.range}", asset: require("${e.rel}") },`).join("\n")}
];
`;
fs.writeFileSync(path.join(root, "src/map/glyphs.generated.ts"), ts);
console.log(`glyphs: ${entries.length} files`);
